# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

env:
  - TOXENV=py27-d19
  - TOXENV=py35-d19

before_install:
  - pip install codecov

install:
  - pip install tox "coverage<4.0" python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -e $TOXENV -- py.test tests --create-db -vv --capture=no --cov=log_deletion --cov-report=xml --cov-config=tests/.coveragerc

after_success:
  - codecov
